spring.application.name=Ms_Carrera
server.port= 8060

#Ubicacion de la BD a la que nos conectaremos
spring.datasource.url=jdbc:mysql://localhost:3306/db_carrera?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuración de Logs (Nivel DEBUG para tu paquete principal)
logging.level.com.smartCampus.Ms_Carrera=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate.orm.jdbc.bind=DEBUG
logging.level.root=WARN

# Configuración de OpenAPI / Swagger UI
# swamper URL: http://localhost:8060/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

logging.level.com.smartcampus.msCarrera=INFO
spring.jpa.open-in-view=false