services:

#Servicio 1: levantar MySQL
  mysql:
    image: mysql:8.4
    container_name: mysql-microservicios
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_estado
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservicios-net

  #Servicio 2: Eureka
  eureka-server:
    build:
      context: ./eurekaserver 
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - microservicios-net

  #1. Ms_Gestion_Estado — no depende de nadie más
  ms-gestion-estado:
    build:
      context: ./Ms_Gestion_Estado/Ms_Gestion_Estado
      dockerfile: Dockerfile
    container_name: ms-gestion-estado
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - gestion-estado

  #2. Ms_Gestion_Usuario — depende de Estado
  ms-gestion-usuario:
    build:
      context: ./MS_Gestión_Usuario/MS_Gestión_Usuario
      dockerfile: Dockerfile
    container_name: ms-gestion-usuario
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-gestion-estado:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - gestion-usuario

  #3. Ms_Confi — depende de Usuario
  ms-confi:
    build:
      context: ./MS_confi 
      dockerfile: Dockerfile
    container_name: ms-confi
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-gestion-usuario:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - confi

  #4. Ms_Asignatura — depende de Estado
  ms-asignatura:
    build:
      context: ./Ms_Asignatura/msAsignatura
      dockerfile: Dockerfile
    container_name: ms-asignatura
    ports:
      - "8070:8070"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-gestion-estado:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - asignatura

  #5. Ms_Carrera — depende de Asignatura y Estado
  ms-carrera:
    build:
      context: ./Ms_Carrera/Ms_Carrera 
      dockerfile: Dockerfile
    container_name: ms-carrera
    ports:
      - "8060:8060"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-gestion-estado:
        condition: service_started
      ms-asignatura:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - carrera

  #6. Ms_curso-seccion — depende de Carrera
  ms-curso-seccion:
    build:
      context: ./Ms_curso-seccion 
      dockerfile: Dockerfile
    container_name: ms-curso-seccion
    ports:
      - "8098:8098"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-carrera:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - curso-seccion
  
  #7. Ms_Gestion_Lista — depende de curso-seccion y Usuario
  ms-gestion-lista:
    build:
      context: ./Ms_Gestión_Lista/Ms_Gestión_Lista 
      dockerfile: Dockerfile
    container_name: ms-gestion-lista
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-curso-seccion:
        condition: service_started
      ms-gestion-usuario:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - gestion-lista

  #8. Ms_Evaluacion — no requiere a nadie
  ms-evaluacion:
    build:
      context: ./Ms_Evaluacion/Ms_Evaluacion
      dockerfile: Dockerfile
    container_name: ms-evaluacion
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - evaluacion

  #9. Ms_cur-eva — depende de curso-seccion y Evaluacion
  ms-cur-eva:
    build:
      context: ./MS_cur_eva 
      dockerfile: Dockerfile
    container_name: ms-cur-eva
    ports:
      - "8099:8099"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-curso-seccion:
        condition: service_started
      ms-evaluacion:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - curso-evaluacion

  #10. Ms_tipo-asistencia — depende de Lista
  ms-tipo-asistencia:
    build:
      context: ./Ms_tipo-asistencia 
      dockerfile: Dockerfile
    container_name: ms-tipo-asistencia
    ports:
      - "8091:8091"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      ms-gestion-lista:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
          aliases:
            - tipo-evaluacion

  #Servicio: apigateway
  api-gateway:
    build:
      context: ./apigateway 
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8021:8021"
    depends_on:
      eureka-server:
        condition: service_started
      ms-gestion-estado:
        condition: service_started
      ms-gestion-usuario:
        condition: service_started
      ms-confi:
        condition: service_started
      ms-asignatura:
        condition: service_started
      ms-carrera:
        condition: service_started
      ms-curso-seccion:
        condition: service_started
      ms-gestion-lista:
        condition: service_started
      ms-evaluacion:
        condition: service_started
      ms-cur-eva:
        condition: service_started 
      ms-tipo-asistencia:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

#almacenamiento persistente
volumes:
  mysql-data:

#crear la red virtual interna
networks:
  microservicios-net:
    driver: bridge