server:
  port: 8021

spring:
  web:
    error:
      include-message: always
      include-stacktrace: always
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: ruta-ms-asignatura
              uri: lb://ms-asignatura
              predicates:
                - Path=/api/asignaturas/**, /api/semestres/**

            - id: ruta-ms-carrera
              uri: lb://ms-carrera
              predicates:
                - Path=/api/carrera-asignaturas/**, /api/carreras/**

            - id: ruta-ms-confi
              uri: lb://ms-confi
              predicates:
                - Path=/auth/**
              
            - id: ruta-ms-cur-eva
              uri: lb://ms-cur-eva
              predicates:
                - Path=/api/cur-eva/**
            
            - id: ruta-ms-curso-seccion
              uri: lb://ms-curso-seccion
              predicates:
                - Path=/api/cursos/**, /api/seccion/**

            - id: ruta-ms-evaluacion
              uri: lb://ms-evaluacion
              predicates:
                - Path=/api/evaluacion/**, /api/tipo-evaluacion/**

            - id: ruta-ms-gestion-estado
              uri: lb://ms-gestion-estado
              predicates:
                - Path=/api/estados/**
            
            - id: ruta-ms-gestion-lista
              uri: lb://ms-gestion-lista
              predicates:
                - Path=/api/calificaciones/**, /api/listas/**

            - id: ruta-ms-gestion-usuario
              uri: lb://ms-gestion-usuario
              predicates:
                - Path=/api/usuarios/**

            - id: ruta-ms-tipo-asistencia
              uri: lb://ms-tipo-asistencia
              predicates:
                - Path=/api/asistencia/**, /api/tipo/**

eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: api-gateway:${server.port}

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG