spring.application.name=Ms_Confi
server.port=8082

# Configuración Avanzada de Logs profesional idéntica a tus servicios
logging.level.Ms.confi=debug
logging.level.org.springframework=warn 
logging.level.root=warn

# Formato de salida para la consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%5level] %logger{30} - %msg%n

ms.usuario.url=http://gestion-usuario:8084

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=Ms-Confi
eureka.instance.instance-id=${spring.application.name}:${server.port}