spring.application.name=Ms_Confi
server.port=8082

# Configuración Avanzada de Logs profesional idéntica a tus servicios
logging.level.Ms.confi=debug
logging.level.org.springframework=warn 
logging.level.root=warn

# Formato de salida para la consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%5level] %logger{30} - %msg%n