spring.application.name=msAsignatura

#Puerto de ejecucion del microservicio
server.port= 8070

#Ubicacion de la BD a la que nos conectaremos
spring.datasource.url=jdbc:mysql://lolcalhost:3306/db_Asigantura

#Usuario y clave para conectarnos a la BD
spring.datasource.username=root
spring.datasource.password=

#Driver a usar segun la BD al conectar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Dialecto, Lenguaje de transformacion para comunicaronos a la BD
spring.jpa.database-platform=org.hibernate.dialect.MysqlDialect

#JPA
#Metodo para la creacion de tablas
#Update: Si no existe las tablas las crea y si existe esta verifica si hay alguna modificacion
spring.jpa.hibernate.ddl-auto=update

#Propiedades para mostrar las sentencias sql que se ejecutan en el microservico internamente
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
