spring.application.name=curso-seccion
server.port=8098

# Configuración de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_curso_seccion?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuración Avanzada de Logs (SLF4J / Logback)
logging.level.com.SCampus.curso_seccion=debug
logging.level.org.springframework=warn 
logging.level.org.hibernate.orm.jdbc.bind=debug
logging.level.root=warn

# Formato de salida de logs para consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%5level] %logger{30} - %msg%n