spring.application.name=curso-seccion
server.port=8090

#Configuracion BD
spring.datasource.url=jdbc:mysql://localhost:3306/db_curso-seccion
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#dialecto - en versiones actuales de mysql no es necesario escribirla
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true